//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appNotificaciones.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class notificaciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public notificaciones()
        {
            this.notificaciones_usuarios = new HashSet<notificaciones_usuarios>();
        }
    
        public int id { get; set; }
        public string titulo { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string mensaje { get; set; }
        public Nullable<bool> eliminado { get; set; }
        public Nullable<bool> leido { get; set; }
        public Nullable<int> id_sistemas { get; set; }
    
        public virtual sistemas sistemas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<notificaciones_usuarios> notificaciones_usuarios { get; set; }
    }
}
