//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appNotificaciones.Entidades
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NotificacionesEntities : DbContext
    {
        public NotificacionesEntities()
            : base("name=NotificacionesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<notificaciones> notificaciones { get; set; }
        public virtual DbSet<notificaciones_usuarios> notificaciones_usuarios { get; set; }
        public virtual DbSet<sistemas> sistemas { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
    }
}
